# Database config
db:
  dbname: 'OptimizerDB'
  user: 'Optimizer'
  password: 'what is password?'
  port: 5432

# Available Technologies:
techs:
  Bardenpho:
    Small:
      Capkt: 4745
      CCkt: 58.44
      OCt: 1.92
      SRWt: 0.13
      GPt: 3.3
    Medium:
      Capkt: 5584865
      CCkt: 8.52
      OCt: 0.59
      SRWt: 0.05
      GPt: 0.39
    Large:
      Capkt: 282801270
      CCkt: 5.43
      OCt: 0.53
      SRWt: 0.41
      GPt: 1.08
  MBR:
    Small:
      Capkt: 4745
      CCkt: 65.01
      OCt: 0.83
      SRWt: 0.13
      GPt: 1.75
    Medium:
      Capkt: 5584865
      CCkt: 9.72
      OCt: 0.26
      SRWt: 0.05
      GPt: 1.33
    Large:
      Capkt: 282801270
      CCkt: 4.49
      OCt: 0.19
      SRWt: 0.41
      GPt: 1.25
  MBR + UF:
    Small:
      Capkt: 4745
      CCkt: 76.58
      OCt: 1.89
      SRWt: 0.83
      GPt: 3.83
    Medium:
      Capkt: 5584865
      CCkt: 12.25
      OCt: 0.58
      SRWt: 0.92
      GPt: 2.91
    Large:
      Capkt: 282801270
      CCkt: 8.20
      OCt: 0.52
      SRWt: 0.92
      GPt: 2.84
  MBR + RO:
    Small:
      Capkt: 4745
      CCkt: 175.14
      OCt: 4.20
      SRWt: 0.83
      GPt: 3.29
    Medium:
      Capkt: 5584865
      CCkt: 25.53
      OCt: 1.06
      SRWt: 0.92
      GPt: 2.87
    Large:
      Capkt: 282801270
      CCkt: 16.27
      OCt: 0.69
      SRWt: 0.92
      GPt: 2.79
  GAC + MF:
    Small:
      Capkt: 4745
      CCkt: 39.01
      OCt: 9.05
      SRWt: 0.13
      GPt: 32.91
    Medium:
      Capkt: 5584865
      CCkt: 5.87
      OCt: 1.08
      SRWt: 0.05
      GPt: 33.21
    Large:
      Capkt: 282801270
      CCkt: 3.17
      OCt: 0.44
      SRWt: 0.40
      GPt: 33.52

# Parameters:
params:
  - Label: 'mu'
    Unit: 'm3/capita-year'
    Value: 118.824
  - Label: 'GTW'
    Unit: 'gr CO2-eq/mi-m3'
    Value: 0.042556
  - Label: 'GTR'
    Unit: 'gr CO2-eq/mi-m3'
    Value: 0.032735
  - Label: 'MG'
    Unit: 'gr CO2-eq/year'
    Value: 1E+50
  - Label: 'CTW'
    Unit: '$/mi-m3'
    Value: 0.1736
  - Label: CTR
    Unit: '$/mi-m4'
    Value: 0.1389
  - Label: 'alpha'
    Unit: 'Ratio'
    Value: 0.9
